version: '3.8'

services:
  homeflix:
    build: .
    container_name: homeflix
    restart: unless-stopped
    ports:
      - "6969:6969"
    volumes:
      - homeflix_cache:/app/cache
      - homeflix_downloads:/app/downloads
      - homeflix_db:/app/data
    environment:
      - TZ=Asia/Ho_Chi_Minh

volumes:
  homeflix_cache:
  homeflix_downloads:
  homeflix_db:
